# 文章更新
name: update-friends-links

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  issues:
  repository_dispatch:
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements #安装requests
      run: |
        pip install -r requirements.txt
    - name: Update links #更新
      run: | 
        python run.py
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
    - name: Commit #更新日志到GitHub仓库
      run: |
        git config --global user.email 2078148078@qq.com
        git config --global user.name TY10909
        git add .
        git commit -m "Successfully Wake" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
